### PR TITLE
fix: Suppress errors during startup of the pose not being available

### PR DESCRIPTION
**Pull request by reinzor**
Wait for a defined timeout of 5 seconds before logging errors. Give the
pose publishing node some time to initialize.

### CODE REVIEW

**Comment by reinzor** [comment]
ping :)

**Comment by reinzor** [comment]
Closing this issue, no response from maintainers

**Comment by maximilianwulf** [comment]
Hi @reinzor 
Sorry for the late reply. Thank you very much for your contribution. 
We addressed the issue in the PR #94 .

**Comment by reinzor** [comment]
Good, thanks for the update

**Pull request closed without merging**
