### PR TITLE
Test/increase fps

### PR DESCRIPTION
**Pull request by mbjelonic**
Hi all, 

we would like to reopen this PR because the update rate of the elevation map is increased.

Best,
Marko

### CODE REVIEW

**Comment by hogabrie** [comment]
Hey marko,
The PR was accidently closed because I deleted the target branch (pre-release).
I am not the right person to review though.
Cheers,
Gabriel

**Comment by mbjelonic** [comment]
@remod , @maximilianwulf : Somehow I am not able to add any reviewers here. Can we please discuss this PR again?

**Comment by maximilianwulf** [comment]
Hi @mbjelonic, thank you for opening this PR again.

In the meantime, we tested the changes on the robot (not measuring the change in fps though) and there is nothing to complain about. 

One last point from my side. The function `SensorProcessorBase::cleanPointCloud` implements:
- removing NaN's
- cutting off points
- and optionally uses the voxelGridFilter.

In my understanding the function `cleanPointCloud` from the base class should implement the common set of functionality for all sensor types. Looking at `StereoSensor` and `LaserSensor` _cutting off points_ is somehow missing. 
Should this then also be added to the other sensor types?

**Comment by maximilianwulf** [comment]
A short recap from the discussion on #96:

This PR introduces:

- A VoxelGrid filter from PCL to reduce points before adding to the grid map.
  - Reduces computation time.
- Added a service, get_raw_submap.

The increase in fps measured is by a factor of 3.4:
- `ElevationMap::add` with unfiltered points: **0.0805s**
- voxel_grid_filter + `ElevationMap::add`: **0.0234s**

No apparent difference of the quality of the elevation map is visible. 

Further filters that could be introduced in a later PR are:
- Filters from libpointmatcher
- Random downsampling filter from PCL
- Skipping points

**Comment by maximilianwulf** [comment]
Since increasing fps is an important topic, it would be nice if someone could profile elevation mapping. With that information available software optimization could be tackled, i.e. using SEE instructions, OpenCL and further parallelization. 

For instance [this](https://github.com/ANYbotics/elevation_mapping/blob/558d925db528a57d21c18202200f43b49ff1a316/elevation_mapping/src/sensor_processors/StructuredLightSensorProcessor.cpp#L89) `for` loop is sequential, although it could be easily computed in parallel since the operations are not depending on each other.

**Comment by jsburklund** [comment]
With the Intel compiler, there is a flag that can be set to get a vectorization report that will list sections that compiled to SIMD instructions, and sections that could possibly be vectorized but weren't and lists the reasons.
https://software.intel.com/en-us/cpp-compiler-auto-vectorization-tutorial-generating-a-vectorization-report

GCC has something equivalent.  This could be used to identify regions that might need slight changes to run significantly faster.
https://www.gnu.org/software/gcc/projects/tree-ssa/vectorization.html#using

It would also be useful to profile the same code with `-ffast-math`, `-funsafe-math-optimizations`, `-march=native`, and/or `-mavx2` flags set. I have noticed some performance boost in other projects by simply compiling for a specific CPU since there are occasionally hacks in the assembly that handle issues with other processors that make the compiled code generic to any x86 CPU. This would also allow the compiler to use the faster instructions for the architecture that the CPU has. E.g. Broadwell vs Haswell has some instructions that run faster.  `-funsafe-math-optimizations` may improve speed by allowing the compiler to rearrange some math operations that should be mathematically equivalent, but may have minor rounding issues and don't comply with IEEE standards.

**Pull request merged**
